# Generated by Django 2.2.5 on 2021-01-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': '리뷰 관리'},
        ),
    ]
