# Generated by Django 2.2.5 on 2021-01-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name_plural': '리스트 관리'},
        ),
    ]
